name: GitHub Action with TeXLive
description: Run arbitrary commands in a TeXLive environment.
author: Cheng Xu
inputs:
  run:
    description: "Arbitrary bash codes to be executed"
    required: true
  texlive_version:
    description: "TeXLive version to use"
  os:
    description: "Base operating system for the TeXLive Docker image ('alpine' or 'debian')"
  scheme:
    description: "The scheme of TeXLive to be used ('full' or 'small')"
  docker_image:
    description: "Custom Docker image to use"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        "${GITHUB_ACTION_PATH}/action.sh"
      env:
        INPUT_RUN: ${{ inputs.run }}
        INPUT_TEXLIVE_VERSION: ${{ inputs.texlive_version }}
        INPUT_OS: ${{ inputs.os }}
        INPUT_SCHEME: ${{ inputs.scheme }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker_image }}
branding:
  icon: book
  color: blue
