name: Test Github Action
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        texlive_version: [2020, 2021, 2022, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Test Action
        uses: ./
        with:
          scheme: small
          texlive_version: ${{ matrix.texlive_version }}
          run: |
            apk add make
            tlmgr install blindtext
            cd test && make
      - name: Check pdf files
        run: |
          file test/test.pdf | grep -q ' PDF '
