name: test
permissions:
  contents: read
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - texlive_version: latest
            os: alpine
            scheme: small
          - texlive_version: latest
            os: debian
            scheme: full
          - texlive_version: 2024
            os: alpine
            scheme: full
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Test Action
        uses: ./
        with:
          texlive_version: ${{ matrix.texlive_version }}
          os: ${{ matrix.os }}
          scheme: ${{ matrix.scheme }}
          run: |
            tlmgr install blindtext
            cd test && make
      - name: Check pdf files
        run: |
          file test/test.pdf | grep -q ' PDF '
